# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game1', '0002_auto_20170327_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
