# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game1', '0003_remove_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
