# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game1', '0007_auto_20170327_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('channelid', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('url', models.URLField()),
                ('pairid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game1.Pairs')),
            ],
        ),
    ]
