# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game1', '0008_channels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='pairs',
            name='channelid',
        ),
        migrations.RemoveField(
            model_name='pairs',
            name='url',
        ),
        migrations.AlterField(
            model_name='pairs',
            name='user1id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid1', to='game1.HID'),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='user2id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid2', to='game1.HID'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
