# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game1', '0009_auto_20170329_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hid',
            name='assid',
            field=models.CharField(max_length=128),
        ),
    ]
