# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game1', '0010_auto_20170329_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channels',
            name='pairid',
        ),
        migrations.AddField(
            model_name='pairs',
            name='channelid',
            field=models.CharField(default=b'something', max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='pairs',
            name='url1',
            field=models.URLField(default=b'test1'),
        ),
        migrations.AddField(
            model_name='pairs',
            name='url2',
            field=models.URLField(default=b'test2'),
        ),
        migrations.DeleteModel(
            name='Channels',
        ),
    ]
